config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users

  resources :users, only: %i[index show]

  resources :games, only: %i[create show] do
    put 'help', on: :member
    put 'answer', on: :member
    put 'take_money', on: :member
  end

  resource :questions, only: %i[new create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Хороший программист — счастливчик!' %></title>
  <%= csrf_meta_tags %>

  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  <![endif]-->

  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <%= link_to 'Billionaire', root_path, class: 'navbar-brand' %>
    <% if user_signed_in? %>
      <div class="navbar-form navbar-right">

        <% if current_user.is_admin? %>
          <%# Ссылка на админку %>
          <%= link_to 'Админка', rails_admin_path, class: 'btn navbar-btn btn-outline-danger btn-xs' %>
          <%= link_to 'Залить новые вопросы', new_questions_path, class: 'btn navbar-btn btn-outline-warning btn-xs' %>
        <% end %>


        <%= link_to content_tag(:span, "#{current_user.name} - #{number_to_currency current_user.balance}"),
                    user_path(current_user),
                    class: 'btn navbar-btn'
        %>
        <%= link_to 'Новая игра', games_path, data: { turbo_method: "post" }, class: 'btn navbar-btn btn-outline-success btn-xs' %>
        <%= link_to 'Выйти', destroy_user_session_path, data: { turbo_method: "delete" }, class: 'btn btn-outline-info btn-xs navbar-btn' %>
      </div>
    <% else %>
      <div class="navbar-form navbar-right">
        <%= link_to 'Войти', new_user_session_path, class: 'btn btn-outline-primary' %>
        <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'btn btn-outline-success' %>
      </div>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-12">
      <%= render partial: "partials/flash" %>
      <%= yield %>
    </div>
  </div>

  <footer class="mt-4 text-right">
    <p>&copy; <%= link_to 'Хороший программист', 'http://bit.ly/1U2DVdI' %> 2016 &mdash; &infin;</p>
  </footer>
</div>

</body>
</html>